<%= IO.read("config/local_database.yml") if File.exists?('config/local_database.yml') %>

production:
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: sqlite3
  database: <%= ENV['TRAVIS'] ? '":memory:"' : 'db/test.sqlite3' %>
  timeout: 500
